services:
  - type: web
    name: cognitive-web-support
    env: python
    buildCommand: pip install -r requirements.txt && python download_models.py
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: us-east-1-aws
      - key: PINECONE_INDEX_NAME
        value: cognitive-support
      - key: REDIS_URL
        fromService:
          type: redis
          name: cognitive-cache
          property: connectionString
      - key: API_KEY
        generateValue: true
      - key: USE_FREE_SEARCH
        value: true
      - key: LOG_LEVEL
        value: INFO
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: CACHE_DURATION_HOURS
        value: 24
      - key: MAX_PAGES_TO_CRAWL
        value: 10
      - key: TOP_K_CHUNKS
        value: 5

  - type: redis
    name: cognitive-cache
    ipAllowList: []
    plan: free
